### ISSUE TITLE
Can't create queue Mpsc is not marked as pub

### ISSUE THREAD

**Issue by rupurt** [tensorush/zig-mpsc#1]
Howdy :wave: 

I'm trying to use this package but I can't `init` a queue because `Mpsc` is not marked as `pub`.

**Comment by tensorush** [comment]
Hi!

You should be able to import the module as the Mpsc struct itself and access `init()` on it directly.
I've just renamed the module from `mpsc` to `Mpsc` to clarify that, too. See commit 2e4e9df.

**Comment by tensorush** [comment]
Here's how you init the queue in your file:

```zig
const Mpsc = @import("Mpsc");

pub fn main() !void {
    var queue: Mpsc = undefined;
    queue.init();
}
```

**Comment by rupurt** [comment]
Great. That works 🙏
